export { default as Login} from "./Login"
export { default as Posts} from "./Posts"
export { default as Register} from "./Register"
export { default as SinglePost} from "./SinglePost"
export { default as EditPostForm} from "./EditPostForm"
export { default as Profile} from "./Profile"
export { default as Message} from "./Message"